// ─── AI-time meter persistence ─────────────────────────────────────
//
// Localstorage-backed store for billable events generated by the chat
// AI-time meter, plus the org-level billing settings (e-billing mode +
// rate increment). Mirrors the REST-endpoint-shaped pattern used by
// documentVaultStore / knowledgePackStore — every function maps 1:1 to
// an endpoint we'll wire later (GET/POST/PATCH/DELETE /billing-events).
//
// US-legal convention: round-up to the nearest 0.1 hr (6 min). Firms
// in jurisdictions requiring quarter-hour units flip the org setting
// to 0.25 hr (15 min). This matches Clio / LeanLaw / CosmoLex defaults.

export type BillingEventStatus = 'draft' | 'approved';

export interface BillingEvent {
  id: string;
  attorneyId: string;
  attorneyName: string;
  attorneyEmail?: string;
  orgId?: string;
  matterName: string;
  clientName?: string;
  activityCode: string;
  activityLabel: string;
  description: string;
  billable: boolean;                // false = tracked but not billed (internal / casual)
  durationSeconds: number;          // raw measured seconds (audit only)
  billableMinutes: number;          // duration rounded up to increment
  billableHours: number;            // billableMinutes / 60, 2dp
  rateIncrementMinutes: 6 | 15;     // snapshot of org setting at save time
  status: BillingEventStatus;
  threadId: string;
  threadTitle?: string;
  startedAt: string;                // ISO
  endedAt: string;                  // ISO
  createdAt: string;                // ISO
  updatedAt?: string;
  notes?: string;
}

export interface OrgBillingSettings {
  eBillingMode: boolean;            // false = custom categories, true = UTBMS
  rateIncrementMinutes: 6 | 15;
}

// ─── Activity catalogs ─────────────────────────────────────────────
// Two flavors: friendly firm categories (default) and UTBMS task+activity
// pairings (e-billing mode). Same dropdown UI, different source.

export interface ActivityOption {
  code: string;
  label: string;
}

export const DEFAULT_ACTIVITY_CATEGORIES: ActivityOption[] = [
  { code: 'RESEARCH',  label: 'Research' },
  { code: 'DRAFTING',  label: 'Drafting' },
  { code: 'REVIEW',    label: 'Document Review' },
  { code: 'ANALYSIS',  label: 'Analysis / Strategy' },
  { code: 'COMM_CLI',  label: 'Client Communication' },
  { code: 'COMM_INT',  label: 'Internal Communication' },
  { code: 'MEETING',   label: 'Meeting / Call' },
  { code: 'COURT',     label: 'Court / Filing' },
  { code: 'NEGOT',     label: 'Negotiation' },
  { code: 'OTHER',     label: 'Other' },
];

// UTBMS pairings (litigation L100-L500 + ABA A101-A111). Not the full
// catalog — the 25 most commonly billed pairs. Sufficient for v1; the
// rest is a Sprint-2 lift once a firm actually flips e-billing on.
export const UTBMS_ACTIVITY_PAIRS: ActivityOption[] = [
  { code: 'L110-A101', label: 'L110 Fact Investigation — A101 Plan and prepare' },
  { code: 'L110-A104', label: 'L110 Fact Investigation — A104 Review/analyze' },
  { code: 'L120-A101', label: 'L120 Analysis/Strategy — A101 Plan and prepare' },
  { code: 'L120-A104', label: 'L120 Analysis/Strategy — A104 Review/analyze' },
  { code: 'L120-A105', label: 'L120 Analysis/Strategy — A105 Communicate (in firm)' },
  { code: 'L120-A106', label: 'L120 Analysis/Strategy — A106 Communicate (with client)' },
  { code: 'L130-A103', label: 'L130 Experts/Consultants — A103 Draft/revise' },
  { code: 'L140-A104', label: 'L140 Document/File Management — A104 Review/analyze' },
  { code: 'L160-A106', label: 'L160 Settlement/Non-Binding ADR — A106 Communicate (with client)' },
  { code: 'L190-A105', label: 'L190 Other Case Assessment — A105 Communicate (in firm)' },
  { code: 'L210-A103', label: 'L210 Pleadings — A103 Draft/revise' },
  { code: 'L210-A104', label: 'L210 Pleadings — A104 Review/analyze' },
  { code: 'L240-A103', label: 'L240 Dispositive Motions — A103 Draft/revise' },
  { code: 'L310-A104', label: 'L310 Written Discovery — A104 Review/analyze' },
  { code: 'L320-A104', label: 'L320 Document Production — A104 Review/analyze' },
  { code: 'L330-A101', label: 'L330 Depositions — A101 Plan and prepare' },
  { code: 'L340-A104', label: 'L340 Expert Discovery — A104 Review/analyze' },
  { code: 'L390-A105', label: 'L390 Other Discovery — A105 Communicate (in firm)' },
  { code: 'L420-A101', label: 'L420 Trial Preparation — A101 Plan and prepare' },
  { code: 'L430-A109', label: 'L430 Court Mandated Conferences — A109 Appear for/attend' },
  { code: 'L440-A111', label: 'L440 Other Trial Preparation — A111 Other' },
  { code: 'L450-A109', label: 'L450 Trial and Hearing Attendance — A109 Appear for/attend' },
  { code: 'L460-A106', label: 'L460 Post-Trial Motions — A106 Communicate (with client)' },
  { code: 'L510-A103', label: 'L510 Appellate Motions — A103 Draft/revise' },
];

export function getActivityCatalog(settings: OrgBillingSettings): ActivityOption[] {
  return settings.eBillingMode ? UTBMS_ACTIVITY_PAIRS : DEFAULT_ACTIVITY_CATEGORIES;
}

// ─── Persistence ───────────────────────────────────────────────────

const EVENTS_KEY = 'yourai_billing_events_v1';
const SETTINGS_KEY = 'yourai_billing_settings_v1';

export function loadEvents(): BillingEvent[] {
  try {
    const raw = localStorage.getItem(EVENTS_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch { return []; }
}

export function saveEvents(events: BillingEvent[]): void {
  try { localStorage.setItem(EVENTS_KEY, JSON.stringify(events)); } catch { /* quota */ }
}

/** Idempotent: if no events stored yet, write the supplied demo seed. */
export function seedEventsIfEmpty(seed: BillingEvent[]): void {
  const existing = loadEvents();
  if (existing && existing.length > 0) return;
  saveEvents(seed);
}

export function addEvent(event: BillingEvent): void {
  const events = loadEvents();
  events.unshift(event);
  saveEvents(events);
}

export function updateEvent(id: string, patch: Partial<BillingEvent>): BillingEvent | null {
  const events = loadEvents();
  const idx = events.findIndex(e => e.id === id);
  if (idx === -1) return null;
  events[idx] = { ...events[idx], ...patch, updatedAt: new Date().toISOString() };
  saveEvents(events);
  return events[idx];
}

export function deleteEvent(id: string): void {
  saveEvents(loadEvents().filter(e => e.id !== id));
}

export function loadSettings(): OrgBillingSettings {
  try {
    const raw = localStorage.getItem(SETTINGS_KEY);
    const base: OrgBillingSettings = { eBillingMode: false, rateIncrementMinutes: 6 };
    if (!raw) return base;
    const parsed = JSON.parse(raw);
    return { ...base, ...parsed };
  } catch { return { eBillingMode: false, rateIncrementMinutes: 6 }; }
}

export function saveSettings(s: OrgBillingSettings): void {
  try { localStorage.setItem(SETTINGS_KEY, JSON.stringify(s)); } catch { /* quota */ }
}

// ─── Helpers ───────────────────────────────────────────────────────

export function roundUpToIncrement(
  seconds: number,
  incrementMinutes: number,
): { billableMinutes: number; billableHours: number } {
  if (seconds <= 0) return { billableMinutes: 0, billableHours: 0 };
  const minutes = seconds / 60;
  const billableMinutes = Math.ceil(minutes / incrementMinutes) * incrementMinutes;
  const billableHours = +(billableMinutes / 60).toFixed(2);
  return { billableMinutes, billableHours };
}

export function formatDuration(seconds: number): string {
  const s = Math.max(0, Math.floor(seconds));
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const sec = s % 60;
  return `${h}:${String(m).padStart(2, '0')}:${String(sec).padStart(2, '0')}`;
}

export function formatBillable(billableMinutes: number): string {
  const hours = billableMinutes / 60;
  return `${hours.toFixed(1)} h`;
}

export function generateEventId(): string {
  return `evt-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}
