import React, { useState } from 'react';
import { Upload, X, FileText, Download, Trash2 } from 'lucide-react';
import { reportTemplates } from '../../data/mockData';
import PageHeader from '../../components/PageHeader';
import Badge from '../../components/Badge';
import Table from '../../components/Table';

export default function ReportTemplates() {
  const [slideOver, setSlideOver] = useState(false);

  return (
    <div className="space-y-6">
      <PageHeader icon={FileText} title="Report Templates" subtitle="Manage deliverables report templates and versions" />
      {/* Active Template */}
      <div>
        <h2 className="mb-4" style={{ fontFamily: "'DM Serif Display', serif", color: 'var(--text-primary)', fontSize: '16px' }}>
          Active Report Template
        </h2>
        <div
          className="bg-white rounded-xl p-6 relative"
          style={{ border: '1px solid var(--border)', boxShadow: '0 1px 4px rgba(0,0,0,0.06)' }}
        >
          {/* Active badge */}
          <div className="absolute top-4 right-4">
            <Badge variant="Active">Currently Active</Badge>
          </div>

          {/* Template Preview */}
          <div className="rounded-lg overflow-hidden" style={{ border: '1px solid var(--border)', maxWidth: 700 }}>
            {/* Header */}
            <div className="px-6 py-3 text-white text-sm font-semibold tracking-wide" style={{ backgroundColor: 'var(--navy)' }}>
              HARTWELL &amp; ASSOCIATES — CONFIDENTIAL
            </div>

            {/* Meta fields */}
            <div className="px-6 py-4 grid grid-cols-2 gap-3" style={{ backgroundColor: 'var(--ice-warm)' }}>
              {['Matter Name', 'Date', 'Prepared By', 'AI Model Used'].map((field) => (
                <div key={field}>
                  <span className="text-xs font-semibold uppercase" style={{ color: 'var(--text-muted)', letterSpacing: '0.05em' }}>
                    {field}
                  </span>
                  <div className="mt-1 h-4 rounded" style={{ backgroundColor: 'var(--ice)', width: '70%' }} />
                </div>
              ))}
            </div>

            {/* Section headers */}
            <div className="px-6 py-4 space-y-3">
              {['Executive Summary', 'Key Findings', 'Risk Analysis', 'Recommendations'].map((section) => (
                <div key={section}>
                  <h4 className="text-sm font-semibold mb-1" style={{ color: 'var(--text-primary)' }}>{section}</h4>
                  <div className="space-y-1.5">
                    <div className="h-3 rounded" style={{ backgroundColor: 'var(--ice)', width: '100%' }} />
                    <div className="h-3 rounded" style={{ backgroundColor: 'var(--ice)', width: '85%' }} />
                    <div className="h-3 rounded" style={{ backgroundColor: 'var(--ice)', width: '60%' }} />
                  </div>
                </div>
              ))}
            </div>

            {/* Footer */}
            <div className="px-6 py-3 text-xs" style={{ backgroundColor: 'var(--ice-warm)', color: 'var(--text-muted)', borderTop: '1px solid var(--ice)' }}>
              AI DISCLAIMER: This report was generated by YourAI. All findings should be reviewed by a qualified attorney.
            </div>
          </div>
        </div>
      </div>

      {/* Upload button */}
      <div>
        <button
          onClick={() => setSlideOver(true)}
          className="px-4 py-2 rounded-lg text-sm font-medium text-white transition-colors flex items-center gap-2"
          style={{ backgroundColor: 'var(--navy)' }}
        >
          <Upload size={16} />
          Upload New Template
        </button>
      </div>

      {/* Template History */}
      <div>
        <h2 className="mb-4" style={{ fontFamily: "'DM Serif Display', serif", color: 'var(--text-primary)', fontSize: '16px' }}>
          Template History
        </h2>
        <Table columns={['Version', 'Description', 'Uploaded By', 'Upload Date', 'Status', 'Actions']}>
          {reportTemplates.map((t) => (
            <tr
              key={t.id}
              className="transition-colors"
              style={{ borderBottom: '1px solid var(--border)' }}
              onMouseEnter={(e) => (e.currentTarget.style.backgroundColor = 'var(--ice-warm)')}
              onMouseLeave={(e) => (e.currentTarget.style.backgroundColor = 'white')}
            >
              <td className="px-4 py-3 text-sm font-medium" style={{ color: 'var(--text-primary)' }}>{t.version}</td>
              <td className="px-4 py-3 text-sm">{t.description}</td>
              <td className="px-4 py-3 text-sm">{t.uploadedBy}</td>
              <td className="px-4 py-3 text-sm" style={{ color: 'var(--text-muted)' }}>{t.date}</td>
              <td className="px-4 py-3"><Badge variant={t.status}>{t.status}</Badge></td>
              <td className="px-4 py-3">
                <div className="flex items-center gap-1">
                  <button className="p-1.5 rounded-lg hover:bg-gray-100 transition-colors" title="Download">
                    <Download size={16} style={{ color: 'var(--slate)' }} />
                  </button>
                  {t.status === 'Archived' && (
                    <button className="p-1.5 rounded-lg hover:bg-red-50 transition-colors" title="Delete">
                      <Trash2 size={16} style={{ color: '#C65454' }} />
                    </button>
                  )}
                </div>
              </td>
            </tr>
          ))}
        </Table>
      </div>

      {/* Slide-over */}
      {slideOver && (
        <div
          className="fixed inset-0 z-50 flex justify-end"
          style={{ backgroundColor: 'rgba(0,0,0,0.4)', backdropFilter: 'blur(4px)' }}
          onClick={() => setSlideOver(false)}
        >
          <div
            className="w-full max-w-md bg-white h-full p-6 overflow-y-auto"
            style={{ boxShadow: '-4px 0 20px rgba(0,0,0,0.1)' }}
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between mb-6">
              <h3 style={{ fontFamily: "'DM Serif Display', serif", color: 'var(--text-primary)', fontSize: '20px' }}>
                Upload New Template
              </h3>
              <button onClick={() => setSlideOver(false)} className="p-1 rounded-lg hover:bg-gray-100">
                <X size={20} style={{ color: 'var(--slate)' }} />
              </button>
            </div>
            <div
              className="rounded-xl p-8 flex flex-col items-center justify-center gap-3"
              style={{ border: '2px dashed var(--ice)' }}
            >
              <Upload size={32} style={{ color: 'var(--text-primary)' }} />
              <p className="text-sm font-medium" style={{ color: 'var(--text-primary)' }}>
                Drag and drop template file
              </p>
              <p className="text-xs" style={{ color: 'var(--text-muted)' }}>PDF, DOCX — Max 50MB</p>
              <button
                className="mt-2 px-4 py-2 rounded-lg text-sm font-medium text-white"
                style={{ backgroundColor: 'var(--navy)' }}
              >
                Browse Files
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
