import { useState, useCallback } from 'react';

const STORAGE_KEY = 'yourai_user_stories';

function load() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch { return []; }
}

function save(stories) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(stories));
}

function nextId(stories) {
  if (stories.length === 0) return 'US-001';
  const nums = stories.map((s) => parseInt(s.id.replace('US-', ''), 10)).filter((n) => !isNaN(n));
  const max = Math.max(0, ...nums);
  return `US-${String(max + 1).padStart(3, '0')}`;
}

export default function useUserStories() {
  const [stories, setStories] = useState(load);

  const refresh = useCallback(() => setStories(load()), []);

  const getAllStories = useCallback(() => stories, [stories]);

  const getStories = useCallback((moduleId) => stories.filter((s) => s.moduleId === moduleId), [stories]);

  const getStory = useCallback((id) => stories.find((s) => s.id === id), [stories]);

  const getModuleCount = useCallback((moduleId) => stories.filter((s) => s.moduleId === moduleId).length, [stories]);

  const createStory = useCallback((data) => {
    const all = load();
    const id = nextId(all);
    const now = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
    const story = { ...data, id, createdAt: now, updatedAt: now };
    const updated = [story, ...all];
    save(updated);
    setStories(updated);
    return story;
  }, []);

  const createMany = useCallback((dataArray, moduleId) => {
    const all = load();
    let currentMax = all.length > 0 ? Math.max(0, ...all.map((s) => parseInt(s.id.replace('US-', ''), 10)).filter((n) => !isNaN(n))) : 0;
    const now = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
    const newStories = dataArray.map((d) => {
      currentMax++;
      return { ...d, id: `US-${String(currentMax).padStart(3, '0')}`, moduleId, createdAt: now, updatedAt: now };
    });
    const updated = [...newStories, ...all];
    save(updated);
    setStories(updated);
    return newStories;
  }, []);

  const updateStory = useCallback((id, data) => {
    const now = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
    const updated = load().map((s) => s.id === id ? { ...s, ...data, updatedAt: now } : s);
    save(updated);
    setStories(updated);
    return updated.find((s) => s.id === id);
  }, []);

  const deleteStory = useCallback((id) => {
    const updated = load().filter((s) => s.id !== id);
    save(updated);
    setStories(updated);
  }, []);

  const duplicateStory = useCallback((id) => {
    const original = load().find((s) => s.id === id);
    if (!original) return null;
    const { id: _, createdAt: __, updatedAt: ___, ...rest } = original;
    return createStory({ ...rest, title: `Copy of ${original.title}`, status: 'Draft', generatedByAI: false });
  }, [createStory]);

  const exportModuleStories = useCallback((moduleId) => {
    const moduleStories = load().filter((s) => s.moduleId === moduleId);
    const blob = new Blob([JSON.stringify(moduleStories, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    const date = new Date().toISOString().split('T')[0];
    a.href = url; a.download = `yourai-user-stories-${moduleId}-${date}.json`; a.click();
    URL.revokeObjectURL(url);
  }, []);

  const exportSingleStory = useCallback((id) => {
    const s = load().find((st) => st.id === id);
    if (!s) return;
    const lines = [
      '═'.repeat(50),
      `${s.id} — ${s.title}`,
      `Module: ${s.moduleId} | Priority: ${s.priority} | Status: ${s.status} | Points: ${s.storyPoints || '—'}`,
      `Generated by AI: ${s.generatedByAI ? 'Yes' : 'No'}`,
      '═'.repeat(50),
      '',
      'USER STORY',
      `As a ${s.role}, I want to ${s.goal}, so that ${s.benefit}.`,
      '',
      'PRECONDITIONS',
      ...(s.preconditions || []).map((p, i) => `${i + 1}. ${p}`),
      '',
      'ACCEPTANCE CRITERIA',
      ...(s.acceptanceCriteria || []).map((c, i) => {
        if (typeof c === 'string') return `${i + 1}. ${c}`;
        return `${i + 1}. Given ${c.given}\n   When ${c.when}\n   Then ${c.then}`;
      }),
      '',
      'ERROR HANDLING',
      ...(s.errorHandling || []).map((e) => typeof e === 'string' ? `• ${e}` : `Scenario: ${e.scenario} → ${e.response}`),
      '',
      'NON-FUNCTIONAL REQUIREMENTS',
      ...(s.nfrs || []).map((n) => `• ${n}`),
      '',
      'TEST SCENARIOS',
      ...(s.testScenarios || []).map((t, i) => `${i + 1}. ${t}`),
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `${s.id}-${s.title.replace(/\s+/g, '-').toLowerCase()}.txt`; a.click();
    URL.revokeObjectURL(url);
  }, []);

  return {
    stories, getAllStories, getStories, getStory, getModuleCount,
    createStory, createMany, updateStory, deleteStory, duplicateStory,
    exportModuleStories, exportSingleStory, refresh,
  };
}
